[server]
port = 80
# mode: "release", "debug", "test"
mode = "debug"

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "password"
database = "gin-boilerplate"
# sslmode: "disable", "allow", "prefer", "require"
sslmode = "disable"

[security]
allowed_hosts = ["localhost"]
sts_seconds = 30758400
sts_include_subdomains = true
frame_deny = true
content_type_nosniff = true
browser_xss_filter = true
content_security_policy = "default-src 'self'"
csrf_secret = "some_secret_key"

[session]
# key: hex encoded 32 byte string
key = "13d45bf0a822b832cc8886fa41ce4ced30584189bad02ec8ce552ace0d1ae8b1"
# enc_key: hex encoded 16 byte string
enc_key = "2bb61a68ac3dec4f7c25efb062f4ae3b"
path = "/"
domain = ""
max_age = 2592000
secure = false
http_only = true
# same_site: Default = 1, Lax = 2, Strict = 3, None = 4
same_site = 1
